import React, { useEffect, useMemo, useState } from 'react';
import { Activity, ArrowUpRight, CheckCircle2, CircleDot, Clock3, GitBranch, Loader2, Play, RotateCcw, Server, Terminal, XCircle } from 'lucide-react';

type Deployment = {
  id: string; projectName: string; repoUrl: string; branch: string; commitSha?: string | null;
  sourceCommit?: string; status: string; createdAt: string; startedAt?: string; completedAt?: string; error?: string;
};

const STATUS: Record<string,{label:string;tone:string;icon:React.ComponentType<{className?:string}>}> = {
  queued:{label:'Queued',tone:'text-amber-300 bg-amber-500/10 border-amber-500/20',icon:Clock3},
  source_validating:{label:'Validating',tone:'text-cyan-300 bg-cyan-500/10 border-cyan-500/20',icon:Loader2},
  building:{label:'Building',tone:'text-violet-300 bg-violet-500/10 border-violet-500/20',icon:Loader2},
  runtime_provisioning:{label:'Provisioning',tone:'text-indigo-300 bg-indigo-500/10 border-indigo-500/20',icon:Loader2},
  health_check:{label:'Health check',tone:'text-blue-300 bg-blue-500/10 border-blue-500/20',icon:Activity},
  ready:{label:'Ready',tone:'text-emerald-300 bg-emerald-500/10 border-emerald-500/20',icon:CheckCircle2},
  retryable_failed:{label:'Retryable failed',tone:'text-orange-300 bg-orange-500/10 border-orange-500/20',icon:RotateCcw},
  terminal_failed:{label:'Failed',tone:'text-rose-300 bg-rose-500/10 border-rose-500/20',icon:XCircle},
};
function StatusBadge({status}:{status:string}){const item=STATUS[status]||{label:status,tone:'text-slate-300 bg-slate-500/10 border-slate-500/20',icon:CircleDot};const Icon=item.icon;return <span className={`inline-flex items-center gap-1.5 rounded-full border px-2.5 py-1 text-[10px] font-semibold ${item.tone}`}><Icon className={`h-3 w-3 ${['building','source_validating','runtime_provisioning'].includes(status)?'animate-spin':''}`}/>{item.label}</span>}

export const DeploymentsTab:React.FC=()=>{
 const [deployments,setDeployments]=useState<Deployment[]>([]),[loading,setLoading]=useState(true),[creating,setCreating]=useState(false),[error,setError]=useState('');
 const [projectName,setProjectName]=useState('velclawhost'),[repoUrl,setRepoUrl]=useState('https://github.com/Velclaw/VelclawHost'),[branch,setBranch]=useState('main');
 const load=async()=>{try{const r=await fetch('/api/v1/deployments',{cache:'no-store'}),p=await r.json();if(!r.ok)throw new Error(p.error||'Không thể tải deployments');setDeployments(Array.isArray(p.deployments)?[...p.deployments].reverse():[]);setError('')}catch(e){setError(e instanceof Error?e.message:'Không thể tải deployments')}finally{setLoading(false)}};
 useEffect(()=>{void load();const t=setInterval(()=>void load(),5000);return()=>clearInterval(t)},[]);
 const counts=useMemo(()=>({total:deployments.length,ready:deployments.filter(x=>x.status==='ready').length,active:deployments.filter(x=>['queued','source_validating','building','runtime_provisioning','health_check'].includes(x.status)).length,failed:deployments.filter(x=>x.status.includes('failed')).length}),[deployments]);
 const deploy=async()=>{setCreating(true);setError('');try{const r=await fetch('/api/v1/deployments',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({projectName,repoUrl,branch})}),p=await r.json();if(!r.ok)throw new Error(p.error||'Deploy failed');await load()}catch(e){setError(e instanceof Error?e.message:'Deploy failed')}finally{setCreating(false)}};
 const retry=async(id:string)=>{const r=await fetch(`/api/v1/deployments/${encodeURIComponent(id)}/execute`,{method:'POST',headers:{'Content-Type':'application/json'},body:'{}'});if(!r.ok){const p=await r.json().catch(()=>({}));setError(p.error||'Retry failed');return}await load()};
 return <section className="space-y-6">
  <div className="flex flex-col gap-4 md:flex-row md:items-end md:justify-between"><div><div className="vc-next-kicker">Deployment platform</div><h1 className="vc-next-title mt-2">Deployments</h1><p className="mt-2 text-sm text-zinc-500">Git → validate → build → runtime → health check, theo mô hình Vercel/Render.</p></div><div className="flex items-center gap-2 text-[11px] text-zinc-500"><span className="h-2 w-2 rounded-full bg-emerald-400 animate-pulse"/> Live control plane</div></div>
  <div className="grid gap-3 sm:grid-cols-4">{[['Deployments',counts.total,'All'],['Ready',counts.ready,'Production'],['In progress',counts.active,'Pipeline'],['Failed',counts.failed,'Needs attention']].map(([label,value,sub])=><div key={String(label)} className="vc-next-surface p-4"><div className="text-[10px] uppercase tracking-widest text-zinc-500">{label}</div><div className="mt-2 text-2xl font-semibold tracking-tight">{value}</div><div className="mt-1 text-[10px] text-zinc-600">{sub}</div></div>)}</div>
  <div className="vc-next-surface p-5"><div className="flex items-center gap-2"><Play className="h-4 w-4 text-violet-400"/><h2 className="text-sm font-semibold">New deployment</h2></div><div className="mt-4 grid gap-3 md:grid-cols-[.8fr_1.6fr_.6fr_auto]"><input value={projectName} onChange={e=>setProjectName(e.target.value)} placeholder="Project name" className="h-10 rounded-lg border px-3 text-sm"/><input value={repoUrl} onChange={e=>setRepoUrl(e.target.value)} placeholder="https://github.com/owner/repo" className="h-10 rounded-lg border px-3 text-sm font-mono"/><input value={branch} onChange={e=>setBranch(e.target.value)} placeholder="main" className="h-10 rounded-lg border px-3 text-sm font-mono"/><button onClick={deploy} disabled={creating} className="inline-flex h-10 items-center justify-center gap-2 rounded-lg bg-white px-4 text-xs font-bold text-black disabled:opacity-50">{creating?<Loader2 className="h-4 w-4 animate-spin"/>:<Play className="h-4 w-4"/>}Deploy</button></div>{error&&<div className="mt-3 rounded-lg border border-rose-500/20 bg-rose-500/5 px-3 py-2 text-xs text-rose-300">{error}</div>}</div>
  <div className="vc-next-surface overflow-hidden"><div className="flex items-center justify-between border-b border-zinc-800 px-5 py-4"><div><h2 className="text-sm font-semibold">Deployment history</h2><p className="mt-1 text-[11px] text-zinc-500">Auto-refresh mỗi 5 giây</p></div><button onClick={()=>void load()} className="rounded-lg border border-zinc-800 p-2 text-zinc-400 hover:text-white" title="Refresh"><RotateCcw className="h-4 w-4"/></button></div>{loading?<div className="flex items-center justify-center gap-2 p-12 text-xs text-zinc-500"><Loader2 className="h-4 w-4 animate-spin"/>Loading deployments</div>:deployments.length===0?<div className="p-12 text-center text-sm text-zinc-500">Chưa có deployment nào.</div>:<div className="divide-y divide-zinc-800">{deployments.map(d=>{const short=(d.sourceCommit||d.commitSha||'').slice(0,7);return <div key={d.id} className="group px-5 py-4 hover:bg-white/[.015]"><div className="flex flex-col gap-3 lg:flex-row lg:items-center lg:justify-between"><div className="min-w-0"><div className="flex flex-wrap items-center gap-2"><StatusBadge status={d.status}/><span className="font-mono text-xs text-zinc-300">{d.projectName}</span><span className="text-zinc-700">/</span><span className="font-mono text-[11px] text-zinc-500">{short||'pending'}</span></div><div className="mt-2 flex flex-wrap items-center gap-3 text-[11px] text-zinc-500"><span className="inline-flex items-center gap-1"><GitBranch className="h-3 w-3"/>{d.branch}</span><span className="inline-flex items-center gap-1"><Server className="h-3 w-3"/>{d.id}</span><span>{new Date(d.createdAt).toLocaleString('vi-VN')}</span></div>{d.error&&<div className="mt-2 text-[11px] text-rose-400">{d.error}</div>}</div><div className="flex items-center gap-2">{d.status.includes('failed')&&<button onClick={()=>void retry(d.id)} className="rounded-lg border border-zinc-700 px-3 py-2 text-[11px] font-semibold text-zinc-300 hover:border-zinc-500">Retry</button>}<button onClick={()=>navigator.clipboard?.writeText(d.id)} className="rounded-lg border border-zinc-800 px-3 py-2 text-[11px] text-zinc-500 hover:text-white"><Terminal className="mr-1 inline h-3 w-3"/>Copy ID</button><ArrowUpRight className="h-4 w-4 text-zinc-700 group-hover:text-zinc-400"/></div></div></div>})}</div>}</div>
 </section>
};